### ISSUE TITLE
Linking up server and their parties

### ISSUE THREAD

**Issue by cmahaffey** [nilocy/resturaunt_app#1]
## user story

  A server should be able to click their name and see all the tables that they must serve
## test statement

 Clicking a server name should direct to parties/index.erb and the url servers/:id/parties
## context and description
- because of the need for an id, there a numerous linking errors that come when I call server.id etc
- I think this at least in par a conceptual problem for me
## error
- expecting way more but for now:
  NoMethodError at /servers/2/parties
  <a href="/servers/<%=@server.id%>/parties/new">Add a party</a>

**Comment by amadden80** [comment]
_In person_
